version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12.x
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm test
  post_build:
    commands:
      - echo Finished build process

artifacts:
  files:
    - lib/*

reports:
  jest_reports:
    files:
      - tests.xml
    file-format: JUNITXML
    base-directory: jest_results
